apiVersion: v1
kind: Namespace
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-pv
  namespace: elasticsearch
spec:
  capacity:
    storage: 30Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /mnt/k8s/elasticsearch
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-pvc
  namespace: elasticsearch
spec:
  resources:
    requests:
      storage: 30Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels: 
      app: elasticsearch
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  namespace: elasticsearch
data:
  ELASTIC_USERNAME: "admin"
  ELASTIC_PASSWORD: "admin1234"
  ES_JAVA_OPTS: "-Xms1g -Xmx1g"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: elasticsearch
  labels:
    app: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
          env:
            - name: discovery.type
              value: single-node
            - name: ELASTIC_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: elasticsearch-config
                  key: ELASTIC_USERNAME
            - name: ELASTIC_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: elasticsearch-config
                  key: ELASTIC_PASSWORD
            - name: ES_JAVA_OPTS
              valueFrom:
                configMapKeyRef:
                  name: elasticsearch-config
                  key: ES_JAVA_OPTS
          resources:
            requests:
              memory: "2Gi"
              cpu: "1000m"
            limits:
              memory: "4Gi"
              cpu: "2000m"
          ports:
            - containerPort: 9200
            - containerPort: 9300
          volumeMounts:
            - name: es-pv
              mountPath: /usr/share/elasticsearch/data
      volumes:
        - name: es-pv
          persistentVolumeClaim:
            claimName: es-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
  namespace: elasticsearch
spec:
  selector: 
    app: elasticsearch
  ports:
    - port: 9200
      targetPort: 9200
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: elasticsearch-ingress
  namespace: elasticsearch
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: elasticsearch.firatyilmaz.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: elasticsearch-service
            port:
              number: 9200
